name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  labelIssues:
    runs-on: ubuntu-latest
    steps:
    - name: Label issue
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['triage']
          })
